# Generated by Django 2.1.5 on 2019-02-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20180727_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='anonymize',
            field=models.BooleanField(default=False, verbose_name='Anonymize'),
        ),
        migrations.AddField(
            model_name='field',
            name='unique',
            field=models.BooleanField(default=False, verbose_name='Unique'),
        ),
        migrations.AlterField(
            model_name='form',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'published'), (3, 'archived')], default=2, verbose_name='Status'),
        ),
    ]
