# Generated by Django 2.1.5 on 2019-02-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20190201_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldentry',
            name='hashed',
            field=models.BooleanField(default=False),
        ),
    ]
