# Generated by Django 2.2 on 2019-05-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_files_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='send_email',
            field=models.BooleanField(default=False, help_text='If checked, the person entering the form will be sent an email', verbose_name='Send email'),
        ),
    ]
